import Link from 'next/link'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">


      <body>
        {/* <header className='border-b mx-2'>
          <div className='flex justify-around items-center p-2'>
            <Link className='border m-1 w-full flex justify-center p-2 rounded-md hover:bg-gray-100 shadow-sm transition-all cursor-pointer' href={`/`}>home</Link>
            <Link className='border m-1 w-full flex justify-center p-2 rounded-md hover:bg-gray-100 shadow-sm transition-all cursor-pointer' href={`/product`}>products</Link>
            <Link className='border m-1 w-full flex justify-center p-2 rounded-md hover:bg-gray-100 shadow-sm transition-all cursor-pointer' href={`/docs`}>docs</Link>
            <Link className='border m-1 w-full flex justify-center p-2 rounded-md hover:bg-gray-100 shadow-sm transition-all cursor-pointer' href={`/login`}>login</Link>
            <Link className='border m-1 w-full flex justify-center p-2 rounded-md hover:bg-gray-100 shadow-sm transition-all cursor-pointer' href={`/register`}>register</Link>
          </div>
        </header> */}

        {children}


        <footer className='fixed bottom-0 w-full mt-2 h-[200px]'>
          <div className='grid grid-cols-3 justify-center items-center gap-2 border h-full'>
            <div className='border flex justify-around items-center'>mobile</div>
            <div className='border flex justify-around items-center'>email</div>
            <div className='border flex justify-around items-center'>address</div>
          </div>
        </footer>
      </body>


    </html>
  )
}
