import { Metadata } from 'next'
import './globals.css'
export const metadata: Metadata = {
  title: {
    default: "nextjs",
    template: "%s | nextjs"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">


      <body>

        {children}

      </body>


    </html>
  )
}
