import Link from "next/link"

export const metadata = {
    title: 'products page',
    description: 'Generated by Next.js',
}

export default function product() {
    return <>
        <h1>product lists</h1>
        <div className="flex flex-col">

            <Link href={`product/1`}>product 1</Link>
            <Link href={`product/2`}>product 2</Link>
            <Link href={`product/3`}>product 3</Link>
        </div>
    </>
}